version: '3'

services:
  mongodb:
    image: mongo:6.0
    # volumes:
    #   - /data/db:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      
  graylog:
    image: graylog/graylog:5.0.6
    volumes:
      - graylog_data:/usr/share/graylog/data
    environment:
      - GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET}
      - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2}
      - GRAYLOG_HTTP_EXTERNAL_URI=http://${GRAYLOG_WEB_HOST}:${GRAYLOG_WEB_PORT}/
      - GRAYLOG_WEB_ENDPOINT_URI=http://${GRAYLOG_WEB_HOST}:${GRAYLOG_WEB_PORT}/api
      - GRAYLOG_ELASTICSEARCH_VERSION=7
    links:
      - mongodb:mongo
      - elasticsearch
    restart: always
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp

volumes:
  static_volume:
  mongo_data:
  es_data:
  graylog_data: