version: '3'

services:
  graylog:
    image: graylog/graylog:5.0.6
    container_name: graylog
    volumes:
      - graylog_data:/usr/share/graylog/data
    environment:
      - GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET}
      - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2}
      - GRAYLOG_HTTP_EXTERNAL_URI=http://${GRAYLOG_WEB_HOST}:${GRAYLOG_WEB_PORT}/
      - GRAYLOG_WEB_ENDPOINT_URI=http://${GRAYLOG_WEB_HOST}:${GRAYLOG_WEB_PORT}/api

      - GRAYLOG_ELASTICSEARCH_VERSION=7
      - GRAYLOG_ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - GRAYLOG_ELASTICSEARCH_DISCOVERY_ENABLED=true
      - GRAYLOG_ELASTICSEARCH_CLUSTER_NAME=graylog
      #- GRAYLOG_ELASTICSEARCH_NETWORK_HOST=10.49.39.163

      - GRAYLOG_MONGODB_URI=${MONGODB_URI}
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      # - GRAYLOG_MONGO_INITDB_ROOT_USERNAME=DATABASE_USER
      # - GRAYLOG_MONGO_INITDB_ROOT_PASSWORD=DATABASE_PASSWORD
    restart: always
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp

volumes:
  static_volume:
  graylog_data:
