version: '3'
services:
  mongodb_container:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27018:27017
    # volumes:
    #   - mongodb_data_container:/data/db
    restart: unless-stopped
    # network_mode: host

# volumes:
#   mongodb_data_container:
